### ISSUE TITLE
Can you do a tutorial on how to convert PC skins to switch skins? Please

### ISSUE THREAD

**Issue by 1243789845** [Guillem96/hollow-knight-nx-skin-converter#1]
Can you do a tutorial on how to convert PC skins to switch skins? Please

**Comment by Guillem96** [comment]
Hi, thanks for opening an issue! (I've also read your email)

I'll try to improve the tutorial that's on the README and see if this works for you. But I can't promise to update it anytime soon. 

You have to know that to convert the skins from PC to NX you have to dump the Hollow Knight ROMfs (https://www.youtube.com/watch?v=BZpK2JT8lcI). There are a lot of guides in the wild on how to do that so I won't deep dive in this part.

I really appriciate your support.

**Comment by 1243789845** [comment]
I know how to dump the Hollow Knight ROMfs,I installed Python 3 and unitypy, downloaded your code base.But I don't know how to use it. If you are willing to publish videos or more detailed tutorials, I am willing to pay for them,Thank you very much
